# Generated by Django 4.2.7 on 2023-11-04 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('run_time', models.IntegerField(null=True)),
                ('rating', models.FloatField(default=0)),
                ('votes', models.IntegerField(default=0)),
                ('description', models.TextField(null=True)),
                ('directors', models.ManyToManyField(to='data.director')),
                ('genres', models.ManyToManyField(to='data.genre')),
                ('stars', models.ManyToManyField(to='data.star')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('start_year', models.CharField(max_length=10, null=True)),
                ('end_year', models.CharField(max_length=10, null=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.media')),
            ],
            options={
                'unique_together': {('media', 'start_year')},
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('year', models.CharField(max_length=10, null=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.media')),
            ],
            options={
                'unique_together': {('media', 'year')},
            },
        ),
    ]
